import { Contact, Property, Deal, Viewing } from '@/types'

export const mockContacts: Contact[] = [
  {
    id: 'c1',
    name: 'Klaus Bauer',
    email: 'k.bauer@gmail.com',
    phone: '+49 176 23456789',
    type: 'buyer',
    status: 'active',
    budget: 650000,
    notes: 'Sucht 4-Zimmer-Wohnung in Berlin-Mitte oder Prenzlauer Berg.',
    created_at: '2024-11-10T08:00:00Z',
  },
  {
    id: 'c2',
    name: 'Sabine Hoffmann',
    email: 'sabine.hoffmann@web.de',
    phone: '+49 151 98765432',
    type: 'seller',
    status: 'active',
    notes: 'Verkauft Erbschaft-Eigentumswohnung in Hamburg.',
    created_at: '2024-11-15T09:30:00Z',
  },
  {
    id: 'c3',
    name: 'Thomas Müller',
    email: 't.mueller@outlook.de',
    phone: '+49 170 11223344',
    type: 'buyer',
    status: 'active',
    budget: 890000,
    notes: 'Interessiert an Einfamilienhaus in München oder Umgebung.',
    created_at: '2024-12-01T11:00:00Z',
  },
  {
    id: 'c4',
    name: 'Anna Schmidt',
    email: 'anna.schmidt@t-online.de',
    phone: '+49 172 55667788',
    type: 'prospect',
    status: 'active',
    budget: 420000,
    notes: 'Erstmalige Käuferin, benötigt Beratung zum Finanzierungsprozess.',
    created_at: '2024-12-05T14:00:00Z',
  },
  {
    id: 'c5',
    name: 'Werner Fischer',
    email: 'w.fischer@gmx.de',
    phone: '+49 163 44556677',
    type: 'seller',
    status: 'active',
    notes: 'Verkauft Gewerbeimmobilie in Frankfurt, zeitkritisch.',
    created_at: '2024-12-08T10:00:00Z',
  },
  {
    id: 'c6',
    name: 'Petra Lange',
    email: 'petra.lange@gmail.com',
    phone: '+49 179 99887766',
    type: 'buyer',
    status: 'active',
    budget: 1200000,
    notes: 'Sucht Luxus-Penthouse in München oder Hamburg.',
    created_at: '2024-12-10T15:30:00Z',
  },
  {
    id: 'c7',
    name: 'Michael Weber',
    email: 'm.weber@yahoo.de',
    phone: '+49 152 33445566',
    type: 'prospect',
    status: 'inactive',
    budget: 380000,
    notes: 'Zurzeit nicht aktiv auf der Suche.',
    created_at: '2024-10-20T09:00:00Z',
  },
  {
    id: 'c8',
    name: 'Ute Braun',
    email: 'ute.braun@web.de',
    phone: '+49 177 12345678',
    type: 'seller',
    status: 'closed',
    notes: 'Verkauf abgeschlossen. Einfamilienhaus in Köln verkauft.',
    created_at: '2024-09-01T08:00:00Z',
  },
  {
    id: 'c9',
    name: 'Jürgen Richter',
    email: 'j.richter@freenet.de',
    phone: '+49 160 87654321',
    type: 'buyer',
    status: 'active',
    budget: 560000,
    notes: 'Interessiert an Mehrfamilienhaus als Kapitalanlage.',
    created_at: '2025-01-05T11:00:00Z',
  },
  {
    id: 'c10',
    name: 'Claudia Neumann',
    email: 'claudia.neumann@gmail.com',
    phone: '+49 174 65432198',
    type: 'prospect',
    status: 'active',
    budget: 750000,
    notes: 'Noch in der Recherchephase, sehr detailorientiert.',
    created_at: '2025-01-12T13:00:00Z',
  },
]

export const mockProperties: Property[] = [
  {
    id: 'p1',
    title: 'Luxus-Penthouse Prenzlauer Berg',
    address: 'Kollwitzstraße 58, 10405 Berlin',
    city: 'Berlin',
    price: 1480000,
    size: 142,
    rooms: 5,
    type: 'apartment',
    status: 'available',
    description: 'Exklusives Penthouse im Herzen von Prenzlauer Berg mit Dachterrasse und Panoramablick.',
    created_at: '2024-11-01T08:00:00Z',
  },
  {
    id: 'p2',
    title: 'Einfamilienhaus Grünwald',
    address: 'Birkenweg 12, 82031 Grünwald',
    city: 'München',
    price: 2100000,
    size: 280,
    rooms: 7,
    type: 'house',
    status: 'reserved',
    description: 'Repräsentatives Einfamilienhaus in begehrter Münchner Südlage mit großem Garten.',
    created_at: '2024-10-15T10:00:00Z',
  },
  {
    id: 'p3',
    title: '3-Zimmer-Wohnung Eppendorf',
    address: 'Eppendorfer Landstraße 91, 20249 Hamburg',
    city: 'Hamburg',
    price: 620000,
    size: 89,
    rooms: 3,
    type: 'apartment',
    status: 'available',
    description: 'Helle, kernsanierte Altbauwohnung im begehrten Eppendorf mit Balkon.',
    created_at: '2024-11-20T09:00:00Z',
  },
  {
    id: 'p4',
    title: 'Gewerbeeinheit Sachsenhausen',
    address: 'Schweizer Straße 44, 60594 Frankfurt am Main',
    city: 'Frankfurt',
    price: 890000,
    size: 210,
    rooms: 0,
    type: 'commercial',
    status: 'available',
    description: 'Vielseitig nutzbare Gewerbeimmobilie in Frankfurts lebendigem Sachsenhausen.',
    created_at: '2024-12-01T11:00:00Z',
  },
  {
    id: 'p5',
    title: 'Doppelhaushälfte Bogenhausen',
    address: 'Oberföhringer Straße 107, 81925 München',
    city: 'München',
    price: 1350000,
    size: 195,
    rooms: 6,
    type: 'house',
    status: 'sold',
    description: 'Gepflegte Doppelhaushälfte in ruhiger Münchner Stadtlage.',
    created_at: '2024-09-10T14:00:00Z',
  },
  {
    id: 'p6',
    title: '2-Zimmer-Wohnung Mitte',
    address: 'Friedrichstraße 120, 10117 Berlin',
    city: 'Berlin',
    price: 480000,
    size: 58,
    rooms: 2,
    type: 'apartment',
    status: 'available',
    description: 'Moderne Stadtwohnung in Berlins Mitte, ideal als Kapitalanlage oder Erstbezug.',
    created_at: '2024-12-10T08:00:00Z',
  },
  {
    id: 'p7',
    title: 'Baugrundstück Potsdam',
    address: 'Am Havelblick 5, 14471 Potsdam',
    city: 'Potsdam',
    price: 380000,
    size: 800,
    rooms: 0,
    type: 'land',
    status: 'available',
    description: 'Erschlossenes Baugrundstück mit herrlichem Blick auf die Havel.',
    created_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'p8',
    title: '4-Zimmer-Altbauwohnung Uhlenhorst',
    address: 'Mundsburger Damm 45, 22087 Hamburg',
    city: 'Hamburg',
    price: 850000,
    size: 125,
    rooms: 4,
    type: 'apartment',
    status: 'reserved',
    description: 'Prachtvolle Altbauwohnung mit Stuckdecken und Parkettboden in Hamburg-Uhlenhorst.',
    created_at: '2024-12-20T09:00:00Z',
  },
]

export const mockDeals: Deal[] = [
  {
    id: 'd1',
    contact: mockContacts[0],
    property: mockProperties[0],
    status: 'viewing',
    value: 1480000,
    commission: 44400,
    notes: 'Zweite Besichtigung geplant.',
    created_at: '2025-01-10T09:00:00Z',
  },
  {
    id: 'd2',
    contact: mockContacts[2],
    property: mockProperties[1],
    status: 'offer',
    value: 2050000,
    commission: 61500,
    notes: 'Angebot unter dem Listenpreis eingereicht. Verhandlung läuft.',
    created_at: '2024-12-15T10:00:00Z',
  },
  {
    id: 'd3',
    contact: mockContacts[5],
    property: mockProperties[7],
    status: 'lead',
    value: 850000,
    commission: 25500,
    notes: 'Erstkontakt über Website. Exposé zugesendet.',
    created_at: '2025-01-15T14:00:00Z',
  },
  {
    id: 'd4',
    contact: mockContacts[7],
    property: mockProperties[4],
    status: 'won',
    value: 1350000,
    commission: 40500,
    notes: 'Notartermin abgeschlossen. Übergabe erfolgreich.',
    created_at: '2024-11-01T08:00:00Z',
  },
  {
    id: 'd5',
    contact: mockContacts[8],
    property: mockProperties[2],
    status: 'viewing',
    value: 620000,
    commission: 18600,
    notes: 'Besichtigung hat sehr gut gefallen.',
    created_at: '2025-01-12T11:00:00Z',
  },
  {
    id: 'd6',
    contact: mockContacts[3],
    property: mockProperties[5],
    status: 'lead',
    value: 480000,
    commission: 14400,
    notes: 'Finanzierungsberatung noch ausständig.',
    created_at: '2025-01-14T15:00:00Z',
  },
  {
    id: 'd7',
    contact: mockContacts[4],
    property: mockProperties[3],
    status: 'offer',
    value: 870000,
    commission: 26100,
    notes: 'Angebot angenommen, Due Diligence läuft.',
    created_at: '2025-01-05T09:00:00Z',
  },
  {
    id: 'd8',
    contact: mockContacts[6],
    property: mockProperties[6],
    status: 'lost',
    value: 380000,
    commission: 0,
    notes: 'Kunde hat sich für ein Objekt bei Mitbewerber entschieden.',
    created_at: '2024-12-01T10:00:00Z',
  },
]

export const mockViewings: Viewing[] = [
  {
    id: 'v1',
    contact: mockContacts[0],
    property: mockProperties[0],
    deal: { id: 'd1', status: 'viewing' },
    date: '2025-06-10',
    time: '14:00',
    status: 'scheduled',
    notes: 'Zweite Besichtigung. Bitte Dachterrasse zeigen.',
    created_at: '2025-01-15T09:00:00Z',
  },
  {
    id: 'v2',
    contact: mockContacts[8],
    property: mockProperties[2],
    deal: { id: 'd5', status: 'viewing' },
    date: '2025-06-11',
    time: '10:30',
    status: 'scheduled',
    notes: 'Interessent kommt mit Architekten.',
    created_at: '2025-01-14T10:00:00Z',
  },
  {
    id: 'v3',
    contact: mockContacts[5],
    property: mockProperties[7],
    deal: { id: 'd3', status: 'lead' },
    date: '2025-06-12',
    time: '15:00',
    status: 'scheduled',
    notes: 'Erstbesichtigung.',
    created_at: '2025-01-15T14:00:00Z',
  },
  {
    id: 'v4',
    contact: mockContacts[2],
    property: mockProperties[1],
    deal: { id: 'd2', status: 'offer' },
    date: '2025-06-05',
    time: '11:00',
    status: 'completed',
    notes: 'Sehr positives Feedback. Käufer sehr interessiert.',
    created_at: '2024-12-10T09:00:00Z',
  },
  {
    id: 'v5',
    contact: mockContacts[6],
    property: mockProperties[6],
    date: '2025-05-28',
    time: '09:30',
    status: 'completed',
    notes: 'Grundstück besichtigt. Käufer hat sich anders entschieden.',
    created_at: '2024-11-25T10:00:00Z',
  },
  {
    id: 'v6',
    contact: mockContacts[9],
    property: mockProperties[0],
    date: '2025-06-13',
    time: '16:00',
    status: 'scheduled',
    notes: 'Interessentin kommt aus München extra für die Besichtigung.',
    created_at: '2025-01-15T15:00:00Z',
  },
  {
    id: 'v7',
    contact: mockContacts[3],
    property: mockProperties[5],
    deal: { id: 'd6', status: 'lead' },
    date: '2025-06-09',
    time: '13:00',
    status: 'scheduled',
    notes: 'Erstkäuferin, ausführliche Erklärungen einplanen.',
    created_at: '2025-01-14T11:00:00Z',
  },
  {
    id: 'v8',
    contact: mockContacts[1],
    property: mockProperties[2],
    date: '2025-05-15',
    time: '10:00',
    status: 'cancelled',
    notes: 'Termin wegen Krankheit abgesagt.',
    created_at: '2024-11-10T09:00:00Z',
  },
]

export const analyticsData = {
  monthlyRevenue: [
    { month: 'Aug', umsatz: 28500, deals: 1 },
    { month: 'Sep', umsatz: 52000, deals: 2 },
    { month: 'Okt', umsatz: 40500, deals: 1 },
    { month: 'Nov', umsatz: 44400, deals: 1 },
    { month: 'Dez', umsatz: 87600, deals: 3 },
    { month: 'Jan', umsatz: 61500, deals: 2 },
  ],
  dealFunnel: [
    { stage: 'Lead', count: 2 },
    { stage: 'Besichtigung', count: 2 },
    { stage: 'Angebot', count: 2 },
    { stage: 'Gewonnen', count: 1 },
    { stage: 'Verloren', count: 1 },
  ],
  topProperties: [
    { name: 'Luxus-Penthouse PB', views: 12, deals: 2 },
    { name: 'Einfamilienhaus Grünwald', views: 9, deals: 1 },
    { name: '3-Zimmer Eppendorf', views: 7, deals: 2 },
    { name: 'Altbauwohnung Uhlenhorst', views: 6, deals: 1 },
    { name: 'Gewerbe Sachsenhausen', views: 5, deals: 1 },
  ],
}
